apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: datagrid
spec:
  security:
    endpointAuthentication: false
    endpointEncryption:
      type: None
  expose:
    type: Route
  service:
    container:
      ephemeralStorage: true
    type: DataGrid
  replicas: 3
  configMapName: datagrid-custom-config
  configListener:
    enabled: false